"""empty message

Revision ID: bb7271d312ce
Revises: 
Create Date: 2019-06-25 19:23:30.577119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb7271d312ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_Cidade_Estado1_idx', table_name='cidade')
    op.drop_table('cidade')
    op.drop_table('ano')
    op.drop_table('estado')
    op.drop_index('fk_RazaoDeExames_Cidade1_idx', table_name='razaodeexames')
    op.drop_index('fk_RazaoDeExames_TipoDeExame1_idx', table_name='razaodeexames')
    op.drop_table('razaodeexames')
    op.drop_index('fk_MamografosPorUF_Estado1_idx', table_name='mamografosporuf')
    op.drop_table('mamografosporuf')
    op.drop_index('fk_Mortalidade_Ano1_idx', table_name='mortalidade')
    op.drop_table('mortalidade')
    op.drop_table('tipodeexame')
    op.drop_index('fk_Exames_Ano1_idx', table_name='exames')
    op.drop_index('fk_Exames_Estado1_idx', table_name='exames')
    op.drop_index('fk_Exames_TipoDeExame1_idx', table_name='exames')
    op.drop_table('exames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exames',
    sa.Column('idExames', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('totalDeExames', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tipoDeCancer', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('Estado_idEstado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('TipoDeExame_idTipoDeExame', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Ano_idAno', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Ano_idAno'], ['ano.idAno'], name='fk_Exames_Ano1'),
    sa.ForeignKeyConstraint(['Estado_idEstado'], ['estado.idEstado'], name='fk_Exames_Estado1'),
    sa.ForeignKeyConstraint(['TipoDeExame_idTipoDeExame'], ['tipodeexame.idTipoDeExame'], name='fk_Exames_TipoDeExame1'),
    sa.PrimaryKeyConstraint('idExames'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_Exames_TipoDeExame1_idx', 'exames', ['TipoDeExame_idTipoDeExame'], unique=False)
    op.create_index('fk_Exames_Estado1_idx', 'exames', ['Estado_idEstado'], unique=False)
    op.create_index('fk_Exames_Ano1_idx', 'exames', ['Ano_idAno'], unique=False)
    op.create_table('tipodeexame',
    sa.Column('idTipoDeExame', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipoDeExame', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idTipoDeExame'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('mortalidade',
    sa.Column('idMortalidade', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('numeroDeCasos', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tipoDeCancer', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('raca', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('FaixaEtaria', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('Ano_idAno', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Ano_idAno'], ['ano.idAno'], name='fk_Mortalidade_Ano1'),
    sa.PrimaryKeyConstraint('idMortalidade'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_Mortalidade_Ano1_idx', 'mortalidade', ['Ano_idAno'], unique=False)
    op.create_table('mamografosporuf',
    sa.Column('idMamografosPorUF', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('quantidadeSUS', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantidadeNaoSUS', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Estado_idEstado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Estado_idEstado'], ['estado.idEstado'], name='fk_MamografosPorUF_Estado1'),
    sa.PrimaryKeyConstraint('idMamografosPorUF'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_MamografosPorUF_Estado1_idx', 'mamografosporuf', ['Estado_idEstado'], unique=False)
    op.create_table('razaodeexames',
    sa.Column('idRazaoDeExames', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nota', mysql.FLOAT(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('TipoDeExame_idTipoDeExame', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Cidade_idCidade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Cidade_idCidade'], ['cidade.idCidade'], name='fk_RazaoDeExames_Cidade1'),
    sa.ForeignKeyConstraint(['TipoDeExame_idTipoDeExame'], ['tipodeexame.idTipoDeExame'], name='fk_RazaoDeExames_TipoDeExame1'),
    sa.PrimaryKeyConstraint('idRazaoDeExames'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_RazaoDeExames_TipoDeExame1_idx', 'razaodeexames', ['TipoDeExame_idTipoDeExame'], unique=False)
    op.create_index('fk_RazaoDeExames_Cidade1_idx', 'razaodeexames', ['Cidade_idCidade'], unique=False)
    op.create_table('estado',
    sa.Column('idEstado', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('sigla', mysql.CHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('idEstado'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ano',
    sa.Column('idAno', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Ano', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idAno'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cidade',
    sa.Column('idCidade', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('latitude', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('longitude', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('Estado_idEstado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Estado_idEstado'], ['estado.idEstado'], name='fk_Cidade_Estado1'),
    sa.PrimaryKeyConstraint('idCidade'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_Cidade_Estado1_idx', 'cidade', ['Estado_idEstado'], unique=False)
    # ### end Alembic commands ###
